### ISSUE TITLE
cannot rename the downloaded file

### ISSUE THREAD

**Issue by bigtan** [iawia002/annie#19] opened 2018-03-19 13:32 UTC
`annie -x http://127.0.0.1:1080 https://www.youtube.com/watch?v=rVEMTxg_LrU`

   Site:   YouTube youtube.com
  Title:   一生所愛《西遊記之仙履奇緣》主题曲 片尾曲 MV   HD 720p
   Type:   video
Quality:   hd720
   Size:   81.63 MiB (85595140 Bytes)

 81.63 MiB / 81.63 MiB [===========================================================================] 100.00% 8.64 MiB/s2018/03/19 21:28:03 rename 一生所愛《西遊記之仙履奇緣》主题曲 片尾曲 MV   HD 720p.mp4.download 一生所愛《西遊記之仙履奇緣》主题曲 片尾曲 MV   HD 720p.mp4: The process cannot access the file because it is being used by another process.

maybe the encoding issue in the file name.

**Comment by iawia002** [comment] 2018-03-19 14:04
hey @bigtan, according to the error message, I don't think it's a file name issue.

the error message says: `The process cannot access the file because it is being used by another process.` I think that's because I didn't close the file, but when I check the code, I do close it. So it's strange, I also tried it on my own computer and didn't reproduce it.

**Comment by bigtan** [comment] 2018-03-19 14:42
refer to this 
`https://stackoverflow.com/questions/35826973/close-the-file-before-rename-it-in-golang`

**Comment by iawia002** [comment] 2018-03-19 14:46
我现在是这样的
https://github.com/iawia002/annie/blob/b55ed16d17e1adc10c14227981d114307f3efe61/downloader/downloader.go#L93
看来应该改成直接关闭好点？
但是我的电脑上不复现很奇怪哎

**Closed** 2018-03-19 15:18 UTC
Labels: bug, help wanted
